<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1552034347257" stop="1552034347286">
  <name>scripts.test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1552034347257" status="passed" stop="1552034347259">
      <name>TestLogin.test_login1</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="28520-MainThread"/>
        <label name="host" value="DESKTOP-5GVIRKP"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1552034347259" status="failed" stop="1552034347286">
      <name>TestLogin.test_login2</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_login.TestLogin object at 0x00000175B6187978&gt;

    def test_login2(self):
&gt;       assert 0
E       assert 0

scripts\test_login.py:5: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="28520-MainThread"/>
        <label name="host" value="DESKTOP-5GVIRKP"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
